version: "3"

services:
  nginx:
    image: nginx:1.21.4
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - flask
  
  flask:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: flask
    command: gunicorn app:app -b 0.0.0.0:8000
    volumes:
      - ./app:/python-docker
    networks:
      my-network:
        aliases:
          - flask-app
          

networks:
  my-network: